spring:
  appliction:
    name: netflixeureka
  security:
    user:
      name: partha
      password: password123

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
